[files]
extend-exclude = [
    "avro",
    "duckdb_pglake/duckdb*",
    "Makefile",
    "Dockerfile",
    "Pipfile*",
    "CMakeLists.txt",
    "test_common/sample",
    "test_common/rest_catalog",
    "**/isolation_schedule",
    "*.control",
    "*.lock",
    "*.sql",
    "*.mk",
    "*.ini",
    "*.patch",
    "*.json",
    "*.csv",
    "*.java",
    "*.avro",
    "*.spec",
    "*.out",
    "pg_lake_table/tests/pytests/test_object_store_catalog.py"
]

[default.extend-identifiers]
make_ands_implicit = "make_ands_implicit"
make_ands_explicit = "make_ands_explicit"
ANDed = "ANDed"
UPDATEs = "UPDATEs"
INSERTs = "INSERTs"
DELETEs = "DELETEs"
WARNINGs = "WARNINGs"

[default.extend-words]
inh = "inh"
opf = "opf"
IYE = "IYE"
IY = "IY"
abd = "abd"
nd = "nd"
Stichting = "Stichting"
ser = "ser"
ba = "ba"
